### ISSUE TITLE
Modlue missing

### ISSUE THREAD

**Issue by bishtnandan** [EyalRozenberg1/SPDCinv#2]
![TechnicalIssue](https://user-images.githubusercontent.com/25434890/195973315-18caf91b-a808-4900-9d92-4a6b1fea791b.jpeg)

**Comment by EyalRozenberg1** [comment]
You need to add the directory to the environment variable PYTHONPATH.
To do so, you can run the following line:  `export PYTHONPATH="${PYTHONPATH}:/home/jupyter/src"`.

You might need to change the path `"/home/jupyter/src"` depending on the location of the folder in your work environment.
